name: Test Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-deploy:
    environment:
      name: test_release
      url: https://test.pypi.org/p/openserver
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest  
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: "Build distribution"
        run: |
          uv build
          uv tool run twine check dist/*
          
      - name: "Publish package distributions to PyPI Test"
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
