name: Test Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-deploy:
    environment:
      name: test_release
      url: https://test.pypi.org/p/openserver
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest  
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:          
          python-version: 3.9
      
      - name: "Installs dependencies"            
        run: |
          python -m pip install --upgrade pip              
          python -m pip install poetry twine
      
      - name: "Build distribution"
        run: |
          poetry build
          twine check dist/*
          
      - name: "Publish package distributions to PyPI Test"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
